.TH EAT 1 
.SH NAME
EAT \- The Edinburgh Associative Thesaurus
.SH SYNOPSIS
.B eat
.br
.B eatshow [-rs]
.br
.B eatindex [-rs]
.nh
.SH DESCRIPTION
The
.I 
Edinburgh Associative Thesaurus
is a database of 
word association norms. The traditional way 
to collect word association norms is to show or say a word to several 
people and ask them to say the word which first comes to their minds 
upon receiving the stimulus. The link established between the stimulus
and the response is not semantically labelled (e.g. as synonym, antonym or 
by a case relation) and can only be regarded 
as an association. These associations can be viewed as a list,
but convey more if represented as a network. Such networks can be 
constructed from the list by a variety of methods including multi-dimensional
scaling, clustering and graph theoretic representation using the 
association values to represent probabilities of stimulus-response
association.
.LP
The Edinburgh association norms were collected by growing the network
from a nucleus set of words. Responses were collected to words
in this nucleus set, then these responses were used to obtain further
responses, and so on. In fact the cycle was repeated about three times
since by then the number of different responses was so large that they could
not be re-used as stimuli. Data collection stopped when 8400 stimulus
words had been used. Each stimulus word was presented to 100 different
subjects, each of whom received 100 words. This gave rise to a total of 55732
nodes in the Thesaurus network. 
.LP
The subjects were mostly
undergraduates from a wide variety of British universities. The age range
of the subjects was from 17 to 22 with a mode of 19. The sex distribution
was 64 per cent male and 36 per cent female. The data was collected between
June 1968 and May 1971.
.LP
The database consists of two sets of files. 
The S-R files - stimulus-response files -
and the R-S files - response-stimulus files.
In each group their are three files making six altogether. The 
.I heads 
file in each group lists the headwords (stimuli or responses) with the number of word
types associated with them, and the total number of tokens of those
associated types. The 
.I concise
files contain the headwords, each type associated with it, and their
frequency of response. For each headword in the file, the headword is
presented on one line followed on the next line by the list of pairs
of associated types and their frequency. Within these lists the types
and frequencies are separated by the bar character (|) which does not 
appear in any entries in the thesaurus. The third type of files are 
the 
.I index
files which are derived from the concise and head files and contain
the information in the head file along with the byte offsets from the
start of the concise file to the
entry for each headword and its associated responses. 
.LP
The index
files can be regenerated using the 
.I eatindex
tool if the byte offset should change for any reason.
.LP
Where words have been truncated to 19 characters to save space
the per cent character (%) has been placed as the 20th.
.LP
The 
.I eatshow
tool can be used to present on the standard output the associates 
from either file to terms entered on the standard input which are
separated by a newline character. The associates are presented with
the headword, the total number of types associated with it and the
total number of tokens associated on one line, then the individual
types and their token counts on the next. The individual types are
ordered by frequency of association with the most frequent first.
.LP
Both tools use flags to indicate which set of files should be searched:
-r for the r-s files, -s for the s-r files. The eatshow tool can be
used iteratively to view the network.
.SH EXAMPLES
To find all the words which are produced as a response to a list
of stimuli, the stimuli should be entered one per line into a file
which should be passed to eatshow using the -s flag, and the responses
will be presented to the standard output:
.LP
eatshow -s < infile > outfile
.LP
To find all the stimuli which produce known responses,
the responses should be entered one per line into a file
which should be passed to eatshow using the -r flag, and the stimuli
will be presented to the standard output:
.LP
eatshow -r < infile > outfile
.SH AUTHOR
The Edinburgh Associative Thesaurus was originally developed
on an Medical Research Council grant to George Kiss, 
then integrated into
the MRC Psycholinguistic Database on a grant to Max Coltheart also
by the MRC. The present version was derived from the file structure
used in this to reduce the file space used while still leaving the 
data in readable ASCII form. It is being made available for general
research use.
.LP
Original Edinburgh Associative Thesaurus: George Kiss, Christine
Armstrong, Robert Milroy and J.R.I. Piper.
.LP
MRC Psycholinguistic Database Version modified by: Max Coltheart,
S. James, J. Ramshaw, B.M. Philip, B. Reid, J. Benyon-Tinker and
E. Doctor. This version was made available by: Philip Quinlan.
.LP
The present version was re-structured and documented by Michael Wilson 
at the Rutherford Appleton Laboratory.
.LP
.SH SEE ALSO
Kiss, G.R., Armstrong, C., Milroy, R., and Piper, J. (1973)
An associative thesaurus of English and its computer analysis.
In Aitken, A.J., Bailey, R.W. and Hamilton-Smith, N. (Eds.), 
.I
The Computer and Literary Studies. 
Edinburgh: University Press.
.LP
Coltheart, M. (1981)
MRC Psycholinguistic Database.
.I
Quarterly Journal of Experimental Psychology,
.B
33A,
497-505.
.SH BUGS
None Known.